# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]
jobs:

  Docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag madhavpasumarthy/dassh
   
    - name: Docker Loginn
      env: 
        Docker_Usr: ${{secrets.DOCKER_USER}}
        Docker_Pwd: ${{secrets.DOCKER_PWD}}
      run: docker login -u $Docker_Usr -p $Docker_Pwd

    - name: push the Docker image
      run: docker push ${{secrets.DOCKER_USER}}/dassh
